### ISSUE TITLE
Problems with the backup

### ISSUE THREAD

**Issue by amiga4everyone** [buanet/ioBroker.docker#181]
I have your ioBroker container running on my Unraid Server. That works very well so far. With its own IP address (mcvlan). But if I try your instructions for updating the container with the help of abackup, I will fail. When I use an empty /opt/iobroker directory with only one backup file in it and also when I try to use a clean ioBroker, install the backup adapter and restore the backup. In the firts way I can't reach the web interface calling IP:8081. In the second way I cant install the Backup. The Backup adapter opens a website IP:8091 but this site isn't reachable and nothing happens. May you can help me. I need a way to update the Container without configuring everything new.  Even if I update to a new major version.

**Comment by buanet** [comment]
Hi,
without any logs there is no way to investigate what's wrong in your case... 

BUT: There are known issues with the backitup adapter and docker at the moment. So it is actually not possible to restore iobroker over the GUI. You have to use the containers console. 
The next thing often goes wrong with restores from other systems is that admin adapter is locked to the ip address of the source system. In this case the container logs might look fine but iobroker admin is not accessible.  

Provide at least container startup log, restore log and view of running processes after container startup. Otherwise  this issue will be closed in 14 days. 

Regards,
André

By the way. Please avoid posting your questions in different channels and give us some time to response. Thank you.
https://forums.unraid.net/topic/101016-support-buanet-iobroker/page/3/?tab=comments#comment-1017883

**Comment by buanet** [comment]
No more response.

**Comment by amiga4everyone** [comment]
Hallo André,

thanks for your Answer. You are right. The Admin adaper Was locked because I gave the new Container a different hostname (--hostname). After changibg this everything works finde. Sorry for the delay.

Sorry if it was wrong to post my problem in the unraid forum. I thougt It could be a unraid specific issue. I didn'd do it for any other reason. Thanks for your great work.
