### ISSUE TITLE
[Problem]: Startup script is trying to remove busy files

### ISSUE THREAD

**Issue by UncleSamSwiss** [buanet/ioBroker.docker#369]
### Description

I'm using ioBroker in BalenaOS (a docker based fleet management). With version 8.0.1 everything was working fine. When I tried to update to v8.1.0 (with balena, you simply update your Dockerfile and deploy the application), the error message below happens and the container exits. This happens in an infinite loop, of course.

My suggestion is: don't fail if `rm` can't delete something in `/tmp`. There might be files that are used by other applications or services running in the container (or as in my case are mounted into `/tmp`, see below).

```sh
mount | grep /tmp
tmpfs on /tmp/balena type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /tmp/resin type tmpfs (rw,nosuid,nodev,mode=755)
```

### Image version

v8.1.0

### Docker logs

```shell
iobroker  --------------------------------------------------------------------------------
 iobroker  -----                   Step 1 of 5: Preparing container                   -----
 iobroker  --------------------------------------------------------------------------------
 iobroker   
 iobroker  Updating Linux packages on first run... Done.
 iobroker  rm: cannot remove '/tmp/balena': Device or resource busy
 iobroker  rm: cannot remove '/tmp/resin': Device or resource busy
```

**Comment by buanet** [comment]
Hi Sam, 
I get your point and will treat this as feature request, not as a problem (with possible hotfix) for the following reasons: 

1. It is absolutely not supported and no good choice to run other services than the ioBroker itself within the ioBroker Docker container. So no other service should write data to /tmp
2. I don't mind a possible reason to mount a host folder to /tmp. 😄 

The startup script tries to `rm -rf /tmp/*` because of keeping the container clean after updating or installing additional packages at the first run of the container. Maybe I can adjust this.

Regards,
André

**Comment by buanet** [comment]
Please test with v9.0.0-beta.2.

**Comment by buanet** [comment]
Stable Release of v9 is available. As I got no feedback to this I assume this is fixed. So I'll close this. 

Regards,
André
